# IP address pool for MetalLB
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.0.0.201-10.0.0.209

---
# L2 advertisement config
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab-l2
  namespace: metallb-system

---
# Memberlist secret for MetalLB
apiVersion: v1
kind: Secret
metadata:
  namespace: metallb-system
  name: memberlist
type: Opaque
data:
  secretkey: Q7oC2iRvjgodFjtZ6CeeAlu1I9QAlW4X3GjRdBwwNYU0IYcdFMUGmvGNXN51Gea569c62GLjQhPPM95hNPRWTBdUL1t32XoahQkB9OkmTpA+RfNmpk3cqoOGm0szi3cnG0DiyKbrlvVdlRKlLWxKU7b4jC8WgnPsKhTzxxYM+Og=
