apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-ds
  namespace: kube-flannel
  labels:
    app: flannel
    k8s-app: flannel
    tier: node
spec:
  selector:
    matchLabels:
      app: flannel
  template:
    metadata:
      labels:
        app: flannel
        tier: node
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - name: kube-flannel
          image: ghcr.io/flannel-io/flannel:v0.26.6
          command: ["/opt/bin/flanneld"]
          args: ["--ip-masq", "--kube-subnet-mgr"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: EVENT_QUEUE_DEPTH
              value: "5000"
          volumeMounts:
            - name: run
              mountPath: /run/flannel
            - name: flannel-cfg
              mountPath: /etc/kube-flannel/
            - name: xtables-lock
              mountPath: /run/xtables.lock
          livenessProbe:
            exec:
              command:
                - cat
                - /run/flannel/subnet.env
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "NET_RAW"]
            privileged: false
      hostNetwork: true
      initContainers:
        - name: install-cni-plugin
          image: ghcr.io/flannel-io/flannel-cni-plugin:v1.6.2-flannel1
          command: ["cp"]
          args: ["-f", "/flannel", "/opt/cni/bin/flannel"]
          volumeMounts:
            - name: cni-plugin
              mountPath: /opt/cni/bin
        - name: install-cni
          image: ghcr.io/flannel-io/flannel:v0.26.6
          command: ["cp"]
          args: ["-f", "/etc/kube-flannel/cni-conf.json", "/etc/cni/net.d/10-flannel.conflist"]
          volumeMounts:
            - name: cni
              mountPath: /etc/cni/net.d
            - name: flannel-cfg
              mountPath: /etc/kube-flannel/
      priorityClassName: system-node-critical
      serviceAccountName: flannel
      tolerations:
        - operator: Exists
          effect: NoSchedule
      volumes:
        - name: run
          hostPath:
            path: /run/flannel
        - name: cni-plugin
          hostPath:
            path: /opt/cni/bin
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: flannel-cfg
          configMap:
            name: kube-flannel-cfg
        - name: xtables-lock
          hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
